comprasTable2/comprasTable2/comprasTable2/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf  import settings
from django.conf.urls.static import  static
from solicitud import views
from solicitud.Reporteador import PostStoreReportesConsulta
from django.contrib.auth.models import User
from django.contrib.auth.models import Group

urlpatterns = [
    path('admin/', admin.site.urls),

    # Solicitud

    path('chaining/', include('smart_selects.urls')),
    path('medicalCompras/', views.menuAcceso, name='medical_Compras'),
    path('validaAcceso/', views.validaAcceso),
    path('Solicitudes/<str:username>, <str:sedeSeleccionada>,<str:nombreUsuario>,<str:nombreSede>,<str:perfil>', views.Solicitudes),
    path('guardarSolicitudes/<str:username>, <str:sedeSeleccionada>,<str:nombreUsuario>, <str:fecha>, <str:nombreSede>,<str:perfil>, <str:area>',       views.guardarSolicitudes),

    path('salir/', views.salir),
    path('solicitudesConsultaTrae/<str:username>, <str:sedeSeleccionada>,<str:nombreUsuario>, <str:nombreSede>,<str:perfil>/', views.PostStoreSolicitudesConsulta.as_view(), name='post_storeSolicitudesConsulta'),
    path('solicitudesConsultaTrae', views.PostStoreSolicitudesConsulta.as_view(), name='post_storeSolicitudesConsulta'),
    path('solicitudesConsulta/<str:username>, <str:sedeSeleccionada>,<str:nombreUsuario>, <str:nombreSede>,<str:perfil>/', views.SolicitudesConsulta, name='SolicitudesConsulta'),
    path('load_dataSolicitudesConsulta/<str:data>/', views.load_dataSolicitudesConsulta, name='load_dataSolicitudesConsulta'),

    # Validacion

    path('ValidacionConsulta/<str:username>,<str:sedeSeleccionada>,<str:nombreUsuario>,<str:nombreSede>,<str:perfil>', views.PostStoreValidacion.as_view(),name='post_storeValidacion'),
    path('ValidacionConsulta/ValidacionBusca/<str:solicitudId>,<str:username>,<str:sedeSeleccionada>,<str:nombreUsuario>,<str:nombreSede>,<str:perfil>/', views.PostStoreValidacion.as_view(),name='post_storeValidacion'),
    path('ValidacionConsulta/ValidacionBusca/', views.PostStoreValidacion.as_view(),name='post_storeValidacion'),
    path('Validacion/post_editValidacion/<int:id>,<str:username>,<str:sedeSeleccionada>,<str:nombreUsuario>,<str:nombreSede>,<str:perfil>,<str:solicitudId>/edit/', views.post_editValidacion, name='post_editValidacion'),
    path('load_dataValidacion/<str:data>', views.load_dataValidacion, name='load_dataValidacion'),

    # Fin Validacion

    # Almacen
    path('AlmacenConsulta/<str:username>,<str:sedeSeleccionada>,<str:nombreUsuario>,<str:nombreSede>,<str:perfil>', views.PostStoreAlmacen.as_view(), name='post_storeAlmacen'),
    path('AlmacenConsulta/', views.PostStoreAlmacen.as_view(), name='post_storeAlmacen'),

    path('load_dataAlmacen/<str:data>', views.load_dataAlmacen, name='load_dataAlmacen'),
    path('AlmacenConsulta/postAlmacen/<int:id>,<str:username>,<str:sedeSeleccionada>,<str:nombreUsuario>,<str:nombreSede>,<str:perfil>,<str:solicitudId>/edit/', views.post_editAlmacen, name='post_editAlmacen'),
    path('postAlmacen/<int:id>/delete', views.post_deleteAlmacen, name='post_deleteAlmacen'),
    path('AlmacenConsulta/AlmacenBusca/postAlmacen/<int:id>/delete', views.post_deleteAlmacen, name='post_deleteAlmacen'),

    # Fin Almacen

    # Compras

    #path('ComprasConsulta/<str:username>, <str:sedeSeleccionada>,<str:nombreUsuario>, <str:nombreSede>,<str:perfil>',  views.ComprasConsulta),
    path('ComprasConsulta/<str:username>,<str:sedeSeleccionada>,<str:nombreUsuario>,<str:nombreSede>,<str:perfil>',  views.PostStoreCompras.as_view() , name='post_storeCompras'),
    path('ComprasConsulta/ComprasBusca', views.PostStoreCompras.as_view(), name='post_storeCompras'),

    path('fetch/>', views.load_dataCompras, name='load_dataCompras'),
    path('load_dataCompras/<str:data>', views.load_dataCompras, name='load_dataCompras'),
    path('ComprasConsulta/postCompras/<int:id>,<str:username>,<str:sedeSeleccionada>,<str:nombreUsuario>,<str:nombreSede>,<str:perfil>,<str:solicitudId>/edit/', views.post_editCompras, name='post_editCompras'),
    #path('postCompras/<int:id>/delete', views.post_deleteCompras, name='post_deleteCompras'),
    #path('ComprasConsulta/ComprasBusca/postCompras/<int:id>/delete', views.post_deleteCompras, name='post_deleteCompras'),

    # Fin Compras

    # Ordenes de Compras
    path('ordenesCompra/<str:username>, <str:sedeSeleccionada>,<str:nombreUsuario>, <str:nombreSede>,<str:perfil>', views.OrdenesCompraConsulta1, name='Compras_Consulta'),
    path('ordenesCompra/OrdenesCompraBusca/', views.PostStoreOrdenesCompra.as_view(),name='post_storeOrdenesCompra' ),
    path('ordenesCompra/OrdenesCompraBusca/<str:pk>,<str:btnEnviarSol>,<str:username>,<str:sedeSeleccionada>,<str:nombreUsuario>,<str:nombreSede>,<str:perfil>/', views.PostStoreOrdenesCompra.as_view(),name='post_storeOrdenesCompra'),
    path('/ordenesCompra/OrdenesCompraBusca/<str:pk>,<str:btnEnviarSol>,<str:username>,<str:sedeSeleccionada>,<str:nombreUsuario>,<str:nombreSede>,<str:perfil>/', views.PostStoreOrdenesCompra.as_view(),name='post_storeOrdenesCompra'),
    path('load_dataOrdenesCompra/<str:solicitudId>', views.load_dataOrdenesCompra, name='load_dataOrdenesCompra'),
    path('descargaArchivo/<str:archivo>', views.descargaArchivo),


    path('ordenesCompraConsultaTrae/<str:username>, <str:sedeSeleccionada>,<str:nombreUsuario>, <str:nombreSede>,<str:perfil>/', views.PostStoreOrdenesCompraConsulta.as_view(), name='post_storeOrdenesCompraConsulta'),
    path('ordenesCompraConsultaTrae', views.PostStoreOrdenesCompraConsulta.as_view(), name='post_storeOrdenesCompraConsulta'),
    path('ordenesCompraConsulta/<str:username>, <str:sedeSeleccionada>,<str:nombreUsuario>, <str:nombreSede>,<str:perfil>/', views.OrdenesCompraConsulta, name='OrdenesCompraConsulta'),
    path('load_dataOrdenesCompraConsulta/<str:data>/', views.load_dataOrdenesCompraConsulta, name='load_dataOrdenesCompraConsulta'),

    # Fin Ordenes de Compras

    ## Reportes
    #path('reportesConsulta/<str:username>, <str:sedeSeleccionada>,<str:nombreUsuario>, <str:nombreSede>,<str:perfil>/', views.ReportesConsulta, name='ReportesConsulta'),
    path('reportesConsultaTrae/<str:username>, <str:sedeSeleccionada>,<str:nombreUsuario>, <str:nombreSede>,<str:perfil>,<str:numeroReporte>/', PostStoreReportesConsulta.as_view(), name='post_storeReportesConsulta'),
    path('reportesConsultaTrae/', PostStoreReportesConsulta.as_view(), name='post_storeReportesConsulta'),
    ## Fin reportes


    ## Pruebas carga Files


    path('ComprasConsulta/descargaArchivoAjax/<int:pk>', views.Simple_Upload, name='post_descargaArchivo'),
    path('ComprasConsulta/descargaArchivoAjax', views.Simple_Upload, name='post_descargaArchivo'),

]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

# Añadir
admin.site.site_header = 'Administracion Medical Compras'
admin.site.site_title = "Portal de Medical Compras"
admin.site.index_title = "Bienvenidos al portal de administración Medical Compras"
admin.site.unregister(User)
admin.site.unregister(Group)

comprasTable2/comprasTable2/solicitud/models.py
from django.db import models

# Create your models here.

from django.utils.timezone import now

# Create your models here.

class SedesCompra(models.Model):
    ACTIVO = 'A'
    INACTIVO = 'I'
    TIPO_CHOICES = (
        (ACTIVO, 'Activo'),
        (INACTIVO, 'Inactivo'),
    )
    id = models.AutoField(primary_key=True)
    codreg_sede = models.CharField(max_length=30, default='')
    nom_sede = models.CharField(max_length=30, default='')
    codreg_ips = models.CharField(max_length=30, default='')
    direccion = models.CharField(max_length=200, default='')
    telefono = models.CharField(max_length=120, default='')
    departamento = models.CharField(max_length=120, default='')
    municipio = models.CharField(max_length=120, default='')
    zona = models.CharField(max_length=120, default='')
    sede = models.CharField(max_length=120, default='')
    estadoreg = models.CharField(max_length=1, default='A', editable=True, choices=TIPO_CHOICES, )

    class Meta:
        unique_together = ("codreg_sede", "nom_sede")

    def __str__(self):
        return self.nom_sede


class Staff(models.Model):
    ACTIVO = 'A'
    INACTIVO = 'I'
    TIPO_CHOICES = (
        (ACTIVO, 'Activo'),
        (INACTIVO, 'Inactivo'),
    )
    GERENCIA = 'G'
    PERFIL = (
        (GERENCIA, 'Gerencia'),
    )
    id = models.AutoField(primary_key=True)
    num_identificacion = models.CharField(max_length=30)
    nom_usuario = models.CharField(max_length=150)
    clave_usuario = models.CharField(max_length=20)
    carg_usuario = models.CharField(max_length=80)
    perfil = models.CharField(max_length=1, default='S', editable=True, choices=PERFIL, )
    sede = models.ForeignKey('solicitud.SedesCompra', on_delete=models.PROTECT, null=True, related_name='ssedesCompra7')
    estadoreg = models.CharField(max_length=1, default='A', editable=True, choices=TIPO_CHOICES, )

    def __str__(self):
        return self.nom_usuario


class Usuarios(models.Model):
    ACTIVO = 'A'
    INACTIVO = 'I'
    TIPO_CHOICES = (
        (ACTIVO, 'Activo'),
        (INACTIVO, 'Inactivo'),
    )
    COMPRAS = 'C'
    ALMACEN = 'A'
    VALIDACION = 'V'
    SOLICITUD = 'S'
    PERFIL = (
        (COMPRAS, 'Compras'),
        (ALMACEN, 'Almacen'),
        (VALIDACION, 'Validacion'),
        (SOLICITUD, 'Solicitud'),
   )
    id = models.AutoField(primary_key=True)
    num_identificacion = models.CharField(max_length=30)
    nom_usuario = models.CharField(max_length=150)
    clave_usuario = models.CharField(max_length=20)
    carg_usuario = models.CharField(max_length=80)
    perfil = models.CharField(max_length=1, default='S', editable=True, choices=PERFIL, )
    sede = models.ForeignKey('solicitud.SedesCompra',  on_delete=models.PROTECT, null=True, related_name='ssedesCompra')
    estadoreg = models.CharField(max_length=1, default='A', editable=True ,choices=TIPO_CHOICES,)

    def __str__(self):
        return self.nom_usuario

class TiposCompra(models.Model):
    ACTIVO = 'A'
    INACTIVO = 'I'
    TIPO_CHOICES = (
        (ACTIVO, 'Activo'),
        (INACTIVO, 'Inactivo'),
    )
    id = models.AutoField(primary_key=True)
    nombre = models.CharField(max_length=30, unique = True)
    descripcion = models.CharField(max_length=150)
    estadoreg = models.CharField(max_length=1, default='A', editable=True ,choices=TIPO_CHOICES,)

    def __str__(self):
        return self.nombre


class Articulos(models.Model):
    ACTIVO = 'A'
    INACTIVO = 'I'
    TIPO_CHOICES = (
        (ACTIVO, 'Activo'),
        (INACTIVO, 'Inactivo'),
    )
    id = models.AutoField(primary_key=True)
    codregArticulo = models.CharField(max_length=30, unique = True)
    articulo = models.CharField(max_length=300,blank= True, null=True, unique = False)
    estadoreg = models.CharField(max_length=1, default='A', editable=True ,choices=TIPO_CHOICES,)

    def __str__(self):
        return self.articulo

class EstadosValidacion(models.Model):
    ACTIVO = 'A'
    INACTIVO = 'I'
    TIPO_CHOICES = (
        (ACTIVO, 'Activo'),
        (INACTIVO, 'Inactivo'),
    )
    id = models.AutoField(primary_key=True)
    nombre = models.CharField(max_length=30, unique = True)
    estadoreg = models.CharField(max_length=1, default='A', editable=True ,choices=TIPO_CHOICES,)

    def __str__(self):
        return self.nombre

class EstadosAlmacen(models.Model):
        ACTIVO = 'A'
        INACTIVO = 'I'
        TIPO_CHOICES = (
            (ACTIVO, 'Activo'),
            (INACTIVO, 'Inactivo'),
        )
        id = models.AutoField(primary_key=True)
        nombre = models.CharField(max_length=30, unique=True)
        estadoreg = models.CharField(max_length=1, default='A', editable=True, choices=TIPO_CHOICES, )

        def __str__(self):
            return self.nombre



class Presentacion(models.Model):
    ACTIVO = 'A'
    INACTIVO = 'I'
    TIPO_CHOICES = (
        (ACTIVO, 'Activo'),
        (INACTIVO, 'Inactivo'),
    )
    id = models.AutoField(primary_key=True)
    nombre = models.CharField(max_length=30, unique = True)
    descripcion = models.CharField(max_length=150)
    estadoreg = models.CharField(max_length=1, default='A', editable=True ,choices=TIPO_CHOICES,)

    def __str__(self):
        return self.nombre


class DescripcionCompra(models.Model):
    ACTIVO = 'A'
    INACTIVO = 'I'
    TIPO_CHOICES = (
        (ACTIVO, 'Activo'),
        (INACTIVO, 'Inactivo'),
    )
    id = models.AutoField(primary_key=True)
    nombre = models.CharField(max_length=30, unique = True)
    descripcion = models.CharField(max_length=150)
    estadoreg = models.CharField(max_length=1, default='A', editable=True ,choices=TIPO_CHOICES,)

    def __str__(self):
        return self.nombre

class Proveedores(models.Model):
    ACTIVO = 'A'
    INACTIVO = 'I'
    TIPO_CHOICES = (
        (ACTIVO, 'Activo'),
        (INACTIVO, 'Inactivo'),
    )
    id = models.AutoField(primary_key=True)
    codreg_proveedor = models.CharField(max_length=50, unique = True)
    proveedor = models.CharField(max_length=80, unique = True)
    nit = models.CharField(max_length=30, unique = True, default='')
    direccion = models.CharField(max_length=80, unique=False, default='')
    telefono = models.CharField(max_length=30,unique=False, default=0)
    correo =  models.EmailField(max_length=200)
    estadoreg = models.CharField(max_length=1, default='A', editable=True ,choices=TIPO_CHOICES,)

    def __str__(self):
        return self.proveedor



class Areas(models.Model):
    ACTIVO = 'A'
    INACTIVO = 'I'
    TIPO_CHOICES = (
        (ACTIVO, 'Activo'),
        (INACTIVO, 'Inactivo'),
    )
    id = models.AutoField(primary_key=True)
    sede = models.ForeignKey('SedesCompra', on_delete=models.PROTECT, null=True, related_name='ssedesArea')
    area        = models.CharField(max_length=80, default='')
    estadoreg = models.CharField(max_length=1, default='A', editable=True, choices=TIPO_CHOICES, )

    def __str__(self):
        return self.area


class Solicitudes(models.Model):
    ACTIVO = 'A'
    INACTIVO = 'I'
    TIPO_CHOICES = (
        (ACTIVO, 'Activo'),
        (INACTIVO, 'Inactivo'),
    )
    id = models.AutoField(primary_key=True)
    fecha = models.DateTimeField(default=now, editable=True)
    usuarios = models.ForeignKey('Usuarios',  on_delete=models.PROTECT, null=True,related_name='uusuarios')
    area = models.ForeignKey('Areas',  on_delete=models.PROTECT, null=True, related_name='aareasSolicitudes')

    estadoreg = models.CharField(max_length=1, default='A', editable=True ,choices=TIPO_CHOICES,)

    def __str__(self):
        return str(self.estadoreg)

class SolicitudesDetalle(models.Model):
    ACTIVO = 'A'
    INACTIVO = 'I'
    TIPO_CHOICES = (
        (ACTIVO, 'Activo'),
        (INACTIVO, 'Inactivo'),
    )


    id = models.AutoField(primary_key=True)
    solicitud = models.ForeignKey('Solicitudes',  on_delete=models.PROTECT, null=True,related_name='ssolicitudes')

    item = models.IntegerField()
    descripcion = models.ForeignKey('DescripcionCompra',  on_delete=models.PROTECT, null=True, related_name='ddescripcion')
    tiposCompra = models.ForeignKey('TiposCompra',  on_delete=models.PROTECT, null=True, related_name='ttipoCompra')
    cantidad =models.IntegerField()
    presentacion = models.ForeignKey('Presentacion', on_delete=models.PROTECT, null=True,
                                     related_name='ppresentacion')
    producto = models.CharField(max_length=30, default='')
    justificacion = models.CharField(max_length=250, default=0)
    estadosSolicitud = models.ForeignKey('EstadosValidacion',  on_delete=models.PROTECT, null=True, related_name='eestadosSolicitud')
    usuarioResponsableValidacion  = models.ForeignKey('Usuarios', on_delete=models.PROTECT, blank=True, null=True,related_name='uusuariosResponsable')
    especificacionesTecnicas = models.CharField(max_length=300, blank=True, null=True, default='')
    estadosValidacion = models.ForeignKey('EstadosValidacion', on_delete=models.PROTECT, null=True,related_name='eestadosValidacion')

    especificacionesAlmacen = models.CharField(max_length=300,blank=True, null=True, default='')
    solicitadoAlmacen = models.IntegerField(default=0)
    entregadoAlmacen = models.IntegerField(default=0)
    usuarioResponsableAlmacen = models.ForeignKey('Usuarios', on_delete=models.PROTECT,blank=True, null=True, related_name='uusuariosResponsableAlmacen')
    estadosAlmacen = models.ForeignKey('EstadosAlmacen',  on_delete=models.PROTECT, null=True, related_name='eestadosAlmacen')
    adjuntoCompras = models.FileField(upload_to="Uploaded Files/", blank=True, null=True)

    observacionesCompras = models.CharField(max_length=300, default='')
    usuarioResponsableCompra = models.ForeignKey('Usuarios',  on_delete=models.PROTECT, blank=True, null=True,    related_name='uusuariosResponsableCompra')
    estadosCompras = models.ForeignKey('EstadosValidacion',  on_delete=models.PROTECT, null=True, related_name='eestadosCompras')

comprasTable2/comprasTable2/templates/accesoPrincipal.html
{% extends "menuAcceso.html" %}
{% load static %}

{% block content %}

    <br>
    <br>
<!-- Container -->
<div id="container">


    <!-- INICIA MODAL -->

    <div class="card">


        <div class="myForm">

            <form id="ModalCaptura" method="POST" onsubmit="return valida(this)">

                <div class="modal fade" id="exampleModal" tabindex="-1"
                     role="dialog" aria-labelledby="exampleModalLabel"
                     aria-hidden="true">
                    <div class="modal-dialog" role="document">
                        <div class="modal-content">
                            <div class="modal-header">
                                <h5 class="modal-title" id="exampleModalLabel">Actualiza
                                    Contraseña</h5>
                                <button type="button" class="close" data-dismiss="modal"
                                        aria-label="Close">
                                    <span aria-hidden="true">&times;</span>
                                </button>
                            </div>
                            <div class="modal-body">

                                <div class="form-group">
                                    <label for="usuario" class="col-form-label">Usuario:</label>
                                    <input type="text" class="form-control" id="usuario" name="usuario"
                                           value="">
                                </div>
                                <div class="form-group">
                                    <label for="contrasenaAnt" class="col-form-label">Contrasena anterior:</label>
                                    <input type="text" class="form-control" id="contrasenaAnt" name="contrasenaAnt"
                                           value="">
                                </div>
                                <div class="form-group">
                                    <label for="contrasenaNueva" class="col-form-label">Nueva contrasena:</label>
                                    <input type="text" class="form-control" id="contrasenaNueva" name="contrasenaNueva"
                                           value="">
                                </div>

                                <div class="form-group">
                                    <label for="contrasenaNueva2" class="col-form-label">De nuevo contrasena:</label>
                                    <input type="text" class="form-control" id="contrasenaNueva2"
                                           name="contrasenaNueva2"
                                           value="">
                                </div>


                            </div>

                            <div class="modal-footer">
                                <span id="mensaje" name="mensaje" style="color:blue">{{Error}}</span>
                                <button type="button" class="btn btn-secondary"
                                        data-dismiss="modal">Close
                                </button>
                                <input type="button" class="btn btn-primary" value="save" onclick="Agrabar1()">
                            </div>
                        </div>
                    </div>
                </div>
            </form>
        </div>


    </div>


    <!-- TERMINA MODAL -->



    <!-- Header -->
    <div id="header">
        <div id="branding">

            <h1 id="site-name"><a href="/admin/"> MEDICAL - COMPRAS </a></h1>

        </div>


    </div>
    <!-- END Header -->


    <div class="main shifted" id="main">


        <div class="content">


            <!-- Content -->
            <div id="content" class="colM">


                <div id="content-main">


                    <form action="/validaAcceso/" method="post" id="login-form"><input type="hidden"
                                                                                       name="csrfmiddlewaretoken"
                                                                                       value="MJ1CwN7LHRoBZUnyQoPpHBnb4M3PwGYmsLJeNsN92l41zY9ZaUPztrhcMWyUTHxc">
                        <div class="form-row">

                            <label class="required" for="id_username">Username:</label> <input type="text"
                                                                                               name="username"
                                                                                               autofocus=""
                                                                                               autocapitalize="none"
                                                                                               autocomplete="username"
                                                                                               maxlength="150"
                                                                                               required=""
                                                                                               id="id_username">
                        </div>
                        <div class="form-row">

                            <label class="required" for="id_password">Password:</label> <input type="password"
                                                                                               name="password"
                                                                                               autocomplete="current-password"
                                                                                               required=""
                                                                                               id="id_password">
                            <input type="hidden" name="next" value="/admin/">
                        </div>

                        <div class="form-row">


                            <label for="seleccion2" class="col-form-label">Sedes:</label>
                            <select id="seleccion2" name="seleccion2">
                                {% for sedes in Sedes %}
                                <option value="{{sedes.codreg_sede}}"> {{sedes.nom_sede}}</option>
                                {% endfor %}
                            </select>
<!--  <label class="required" for="id_perfil">Perfil:</label> <input type="text" name="perfil" autofocus="" autocapitalize="none" autocomplete="perfil" maxlength="150" required="" id="id_perfil">  -->

                        </div>


                <!--
                        <div class="form-row">


                            <label for="seleccion1" class="col-form-label">Seleccione Perfil:</label>
                            <select id="seleccion1" name="seleccion1">
                                {% for perfiles in Perfiles %}
                                <option value="{{perfiles.codreg_perfil}}"> {{perfiles.nom_perfil}}</option>
                                {% endfor %}
                            </select>


                        </div>

                     -->
                          <!--  <label class="required" for="id_perfil">Perfil:</label> <input type="text" name="perfil" autofocus="" autocapitalize="none" autocomplete="perfil" maxlength="150" required="" id="id_perfil">  -->
                        <span id="error" name="error" style="color:blue">{{Error}}</span>


                        <div class="submit-row">
                            <input type="submit" value="Log in">
                        </div>
                    </form>

                </div>


                <br class="clear">
            </div>
            <!-- END Content -->
            <div id="footer">
                <!--		<a  href="/findOne/19456673 ,75AAbb??" role="button" class="btn btn-primary eBtn" data-toggle="modal" onclick="$('#exampleModal').modal('show')"> Cambio Contrasena</a> -->

            </div>
        </div>
    </div>
</div>
<!-- END Container -->

<script>

  function Agrabar1()
{

	var envios = new FormData();




	var username = document.getElementById("usuario").value;

	var contrasenaAnt = document.getElementById("contrasenaAnt").value;
	var contrasenaNueva = document.getElementById("contrasenaNueva").value;
	var contrasenaNueva2 = document.getElementById("contrasenaNueva2").value;




<!--
window.location.pathname,
-->

	$.ajax({
		type: 'POST',
    	url: '/grabar1/username,contrasenaAnt,contrasenaNueva,contrasenaNueva2',
		data: {'username':username,'contrasenaAnt':contrasenaAnt, 'contrasenaNueva':contrasenaNueva, 'contrasenaNueva2': contrasenaNueva2},
		success: function (respuesta) {




            	document.getElementById("mensaje").innerHTML = respuesta;
            	  $('#error').val(respuesta);
			$('#exampleModal1').modal().hide();
			<!-- window.location.reload(); -->
             $('#error').val(respuesta);
             	document.getElementById("error").innerHTML = respuesta;

                    },
	   		    error: function (request, status, error) {
	   	    	}
	});
};

</script>


{% endblock %}

comprasTable2/comprasTable2/templates/menuAcceso.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <script src={% static 'main.js' %} defer> </script>
    <title>
        {% block title %} {% endblock %}
    </title>

<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>

    <!-- Custom css -->
    <link rel="stylesheet" type="text/css"  href = {% static 'css/login.css' %} >
    <link rel="stylesheet" type="text/css"  href = {% static 'css/nav_sidebar.css' %} >
    <link rel="stylesheet" type="text/css"  href = {% static 'js/nav_sidebar.js' %} >
    <link rel="stylesheet" type="text/css"  href = {% static 'css/base.css' %} >
    <link rel="stylesheet" type="text/css"  href = {% static 'css/responsive.css' %} >

</head>

<body class=" login" data-admin-utc-offset="0"  ">
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container-fluid">
    <a class="navbar-brand" href="#">Clinica Medical</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
       <div class="navbar-nav">
        <a class="nav-link active" aria-current="page" href="#">Mision</a>
  <!--    <a class="nav-link" href="/contrasena#">Contraseña</a> -->
<a  class="nav-link" href="/findOne/19456673 ,75AAbb??"   data-toggle="modal" onclick="$('#exampleModal').modal('show')"></a>


        <a class="nav-link disabled" href="#" tabindex="-1" aria-disabled="true">Disabled</a>

      </div>
    </div>
  </div>
</nav>

{% block content  %}


{% endblock %}



<script>

var $ = jQuery;

 $(document).ready(function(){


  });


</script>
</body>

</html>